sudo: false
language: perl
perl:
   - '5.14'
   - '5.16'
   - '5.18'
   - '5.20'
   - '5.21'
env:
   - BUILD=0
   - BUILD=1
matrix:
   allow_failures:
      - perl: '5.21'
   fast_finish: true
branches:
   only: /^build\/.*/
before_install:
   - rm .travis.yml
   - export AUTHOR_TESTING=0
install:
   - cpanm --installdeps --verbose --notest .
