sudo: false
language: perl
perl:
   - '5.8'
   - '5.10'
   - '5.12'
   - '5.14'
   - '5.16'
   - '5.18'
   - '5.20'
   - '5.22'
   - 'dev'
   - 'blead'
matrix:
  include:
    - perl: 5.18
      env: COVERAGE=1   # enables coverage+coveralls reporting
  allow_failures:
    - perl: dev
    - perl: blead
  fast_finish: true
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto