sudo: false
language: perl
perl:
   - '5.14'
   - '5.16'
   - '5.18'
   - '5.20'
   - '5.21'
env:
   - BUILD=0
   - BUILD=1
matrix:
   allow_failures:
      - env: BUILD=0
        perl: '5.21'
      - env: BUILD=1
        perl: '5.21'
   fast_finish: true
before_install:
   - 'if [[ $BUILD == 1 && ! -d .build/testing ]]; then unset BUILD; fi'
   - export AUTOMATED_TESTING=1 NONINTERACTIVE_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
   - git clone git://github.com/haarg/perl-travis-helper
   - source perl-travis-helper/init
   - build-perl
   - perl -V
   - 'if [[ $BUILD == 0 ]]; then git config --global user.name "TravisCI"; fi'
   - 'if [[ $BUILD == 0 ]]; then git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"; fi'
   - 'if [[ $BUILD == 1 ]]; then cd .build/testing; fi'
   - 'if [[ $BUILD == 1 ]]; then export AUTHOR_TESTING=0; fi'
install:
   - 'if [[ $BUILD == 0 ]]; then cpanm --quiet --notest --skip-satisfied Dist::Zilla; fi'
   - "if [[ $BUILD == 0 ]]; then dzil authordeps          --missing | grep -vP '[^\\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest; fi"
   - "if [[ $BUILD == 0 ]]; then dzil listdeps   --author --missing | grep -vP '[^\\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest; fi"
   - 'if [[ $BUILD == 1 ]]; then cpanm --installdeps --verbose --notest .; fi'
script:
   - 'if [[ $BUILD == 0 ]]; then dzil smoke --release --author; fi'
   - 'if [[ $BUILD == 1 && -f Makefile.PL ]]; then perl Makefile.PL && make test;    fi'
   - 'if [[ $BUILD == 1 && -f Build.PL    ]]; then perl Build.PL    && ./Build test; fi'
   - 'if [[ $BUILD == 1 && ! -f Makefile.PL && ! -f Build.PL ]]; then  make test;    fi'
