branches:
  only:
    - master
sudo: false
language: perl
perl:
   - '5.8'
   - '5.10'
   - '5.12'
   - '5.14'
   - '5.16'
   - '5.18'
   - '5.20'
   - '5.22'
   - 'dev'
   - 'blead'
#env:
#  - COVERAGE=1
matrix:
  allow_failures:
    - perl: 'dev'
    - perl: 'blead'
    # Kavorka needs 5.14
    - perl: '5.8'
    - perl: '5.10'
    - perl: '5.12'
  fast_finish: true
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
