sudo: false
language: perl
perl:
   - 5.14.0
   - 5.14.1
   - 5.14.2
   - 5.14.3
   - 5.14.4
   - 5.16.0
   - 5.16.1
   - 5.16.2
   - 5.16.3
   - 5.18.0
   - 5.18.1
   - 5.18.2
   - 5.20.0
   - 5.20.1
   - 5.20.2
   - 5.22.0
   - 5.22.1
   - dev
   - 'blead'
env:
   - BUILD=0
   - BUILD=1
matrix:
   allow_failures:
      - perl: dev
      - perl: 'blead'
   fast_finish: true
branches:
   only: /^build\/.*/
before_install:
   - rm .travis.yml
   - export AUTHOR_TESTING=0
install:
   - cpanm --installdeps --verbose --notest .
