language: perl
perl:
   - '5.14'
   - '5.16'
   - '5.18'
   - '5.20'
   - dev
   - 'blead'
env:
   - BUILD=0
   - BUILD=1
matrix:
   allow_failures:
      - perl: dev
      - perl: 'blead'
   fast_finish: true
branches:
   only: /^build\/.*/
before_install:
   - export AUTOMATED_TESTING=1 NONINTERACTIVE_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
   - git clone git://github.com/haarg/perl-travis-helper
   - source perl-travis-helper/init
   - build-perl
   - perl -V
   - rm .travis.yml
   - export AUTHOR_TESTING=0
install:
   - cpanm --installdeps --verbose --notest .
