sudo: false
language: perl
perl:
   - 5.14.0
   - 5.14.1
   - 5.14.2
   - 5.14.3
   - 5.14.4
   - 5.16.0
   - 5.16.1
   - 5.16.2
   - 5.16.3
   - 5.18.0
   - 5.18.1
   - 5.18.2
   - 5.20.0
   - 5.20.1
   - 5.20.2
   - 5.22.0
   - 5.22.1
   - dev
   - 'blead'
env:
   - BUILD=0
   - BUILD=1
matrix:
   allow_failures:
      - perl: dev
      - perl: 'blead'
   fast_finish: true
before_install:
   - export AUTOMATED_TESTING=1 NONINTERACTIVE_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
   - git clone git://github.com/haarg/perl-travis-helper
   - source perl-travis-helper/init
   - build-perl
   - perl -V
   - rm .travis.yml
   - export AUTHOR_TESTING=0
install:
   - cpanm --installdeps --verbose --notest .
