---
abstract: 'Object Orientated Interface to CloudFlare client API'
author:
  - 'Peter Roberts <me+dev@peter-r.co.uk>'
build_requires:
  File::Spec: '0'
  HTTP::Response: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  IPC::System::Simple: '0'
  JSON::Any: '0'
  Test::CPAN::Meta::JSON: '0'
  Test::Exception: '0'
  Test::LWP::UserAgent: '0'
  Test::Moose: '0'
  Test::More: '0'
  Test::RequiresInternet: '0'
  Test::TypeTiny: '0'
  Try::Tiny: '0'
  blib: '1.01'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.043, CPAN::Meta::Converter version 2.150005'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CloudFlare-Client
provides:
  CloudFlare::Client:
    file: lib/CloudFlare/Client.pm
    version: v0.55.5
  CloudFlare::Client::Exception::Connection:
    file: lib/CloudFlare/Client/Exception/Connection.pm
    version: v0.55.5
  CloudFlare::Client::Exception::Upstream:
    file: lib/CloudFlare/Client/Exception/Upstream.pm
    version: v0.55.5
  CloudFlare::Client::Types:
    file: lib/CloudFlare/Client/Types.pm
    version: v0.55.5
requires:
  JSON::MaybeXS: '0'
  Kavorka: '0'
  LWP::Protocol::https: '6.02'
  LWP::UserAgent: '6.02'
  Moose: '0'
  MooseX::StrictConstructor: '0'
  Readonly: '0'
  Throwable::Error: '0'
  Type::Library: '0'
  Type::Utils: 0.039_12
  Types::Standard: '0'
  indirect: '0'
  mro: '0'
  namespace::autoclean: '0'
  perl: '5.014'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/pwr22/cloudflare-client/issues
  homepage: https://metacpan.org/pod/CloudFlare::Client
  repository: git://github.com/pwr22/cloudflare-client.git
version: v0.55.5
x_contributors:
  - 'Peter Roberts <me+github@peter-r.co.uk>'
